### ISSUE TITLE
Please change NTAreas.bat del dir

### ISSUE THREAD

**Issue by agb1** [RoxanneSHS/NTotSCEET-Interim#1]
The NTAreas.bat script ends with this line:

  del dir NTotSC1

This should be changed to:

  rmdir /Q /S NTotSC1

In its current form, it tries to delete non-existent file "dir" followed by prompting if you are sure you want to delete NTotSC1.  This is troublesome for BWS installs because the prompt halts the installation process.

With the change, it will delete the folder and contents quietly, no prompt.

**Comment by RoxanneSHS** [comment]
Done
I trust you in this, I have not tested it myself. Just from the look of it I think it is correct.
